language: c

dist: 
 - bionic

# Setup Build Matrix
compiler: 
 - clang
 - gcc

env:
  global:
    - CONFIGURE_FLAGS="--enable-video --enable-conference --enable-distributed-devicestate --enable-advanced-functions --enable-experimental-xml --with-hash-size=3001"
    - COVERITY_SCAN_PROJECT_NAME="chan-sccp/chan-sccp"
    - COVERITY_SCAN_PROJECT_DESCRIPTION="SCCP Channel Addon for Asterisk"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="info@talon.nl"
    - COVERITY_SCAN_BRANCH_PATTERN="develop"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="./configure --enable-video --enable-conference --enable-distributed-devicestate --enable-advanced-functions --enable-experimental-xml && make clean"
    - COVERITY_SCAN_BUILD_COMMAND="make -j2"
    - COVERITY_SCAN_BUILD_URL="https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
    - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created using: travis encrypt COVERITY_SCAN_TOKEN="xxxxxxx-xxxxxxx" -r dkgroot/chan-sccp-b
    - secure: "ambC8BbKKCJRW/6iwwNS7xfcAg2X00jZsK0McvwpFUEBylxypUni2aBdOpOyMcUGd5hQJS16XbcObeBCim2ZYnyAUzR2LKoFZroGVbwN83OhLGJ83cSXgiDbzKUxuBKTwonUocB7HxWuFJLN1OXb9gucwQNWbLC2VuV5tTsp/NY="
  matrix:
    #- REPOS=xenial   # TLS
    - REPOS=coverity # bionic TLS
    - REPOS=bionic   # TLS
    - REPOS=focal

matrix:
  allow_failures:
    - compiler: clang
      env: REPOS=coverity

# Install Required Devel Packages
before_install:
 - if [ "${REPOS}" != "coverity" ]; 
   then
     sudo apt-get update -qq;
     sudo apt-get install -qq libblocksruntime0 libblocksruntime-dev libpj2 libpjmedia2 libpjnath2 libpjproject-dev libpjsip2 libpjsua2 asterisk asterisk-dev asterisk-config asterisk-modules binutils.dev libc6-dev gettext  autoconf automake m4 autotools-dev libltdl-dev;
   else
     sudo apt-get update -qq;
     sudo apt-get install -qq libblocksruntime0 libblocksruntime-dev libpj2 libpjmedia2 libpjnath2 libpjproject-dev libpjsip2 libpjsua2 asterisk asterisk-dev asterisk-config asterisk-modules binutils.dev libc6-dev gettext  autoconf automake m4 autotools-dev libltdl-dev;
     if [ "x${CC}" == "xclang" ] && [ "x${TRAVIS_BRANCH}" == "xdevelop" ]; then 
      eval "$COVERITY_SCAN_BUILD" || exit 0;
     fi;
   fi

# Prepare Configure Script
before_script:
 - autoreconf -fi

# Note that we use "make -k" to do the entire build, even if there was a
# build error in there somewhere.  This prevents us from needing to submit
# to Travis, see the first error, fix that first error, submit again, ...etc.
script:
  - ./configure ${CONFIGURE_FLAGS} || travis_terminate 1
  - make -k || travis_terminate 1
  - make test  || travis_terminate 1 

#after_script:
# - cat /home/travis/build/chan-sccp/chan-sccp/cov-int/scm_log.txt
# Report Results
notifications:
  slack: chan-sccp:yfQzKYTnTf4cD1iHElnTYsXD
  email:
    recipients:
      - ddegroot@talon.nl
      #- marcelloceschia@users.sourceforge.net
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9866d73035951354e5a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
